- name: debug
  ansible.builtin.debug:
    msg:
      - "createlxc_api_user: {{ createlxc_api_user }}"
      - "createlxc_api_password: {{ createlxc_api_password }}"
      - "createlxc_api_token_secret: {{ createlxc_api_token_secret }}"
      - "createlxc_api_token_id: {{ createlxc_api_token_id }}"
      - "createlxc_api_host: {{ createlxc_api_host }}"
      - "createlxc_node: {{ createlxc_node }}"
      - "createlxc_pool: {{ createlxc_pool | default(omit) }}"
      - "createlxc_validate_certs: {{ createlxc_validate_certs }}"
      - "createlxc_vmid: {{ createlxc_vmid | default(omit) | int }}"
      - "createlxc_hostname: {{ createlxc_hostname }}"
      - "createlxc_description: {{ createlxc_description }}"
      # start vm after creation
      - "createlxc_startup: {{ createlxc_startup }}"
      - "createlxc_onboot: {{ createlxc_onboot }}"
      # createlxc_clone_type: "" # linked | full
      - "createlxc_unprivileged: {{ createlxc_unprivileged }}"
      - "createlxc_state: {{ createlxc_state }}"
      - "createlxc_force: {{ createlxc_force }}"
      - "createlxc_update: {{ createlxc_update }}"
      #  template name
      - "createlxc_ostemplate: {{ createlxc_ostemplate }}"
      - "createlxc_ostype: {{ createlxc_ostype }}"
      #  cpu
      - "createlxc_cpus: {{ createlxc_cpus }}"
      - "createlxc_cores: {{ createlxc_cores }}"
      # - "createlxc_cpuunits: {{ createlxc_cpuunits }}"
      #  memory
      - "createlxc_memory: {{ createlxc_memory }}"
      - "createlxc_swap: {{ createlxc_swap }}"
      #  disk
      - "createlxc_storage: {{ createlxc_storage }}"
      - "createlxc_disk_storage: {{ createlxc_disk_storage }}"
      - "createlxc_disk_size: {{ createlxc_disk_size }}"
      - "createlxc_disk_opt_volume: {{ createlxc_disk_opt_volume }}"
      - "createlxc_disk_opt_acl: {{ createlxc_disk_opt_acl }}"
      - "createlxc_disk_opt_mountoptions: {{ createlxc_disk_opt_mountoptions }}"
      - "createlxc_disk_opt_quota: {{ createlxc_disk_opt_quota }}"
      - "createlxc_disk_opt_replicate: {{ createlxc_disk_opt_replicate }}"
      - "createlxc_disk_opt_ro: {{ createlxc_disk_opt_ro }}"
      - "createlxc_disk_opt_shared: {{ createlxc_disk_opt_shared }}"
      - "createlxc_disk: {{ createlxc_disk }}"
      - "createlxc_mounts: {{ createlxc_mounts }}"
      - "createlxc_disk_volume: {{ createlxc_disk_volume }}"
      - "createlxc_mount_volumes: {{ createlxc_mount_volumes }}"
      # network
      - "createlxc_nameservers: {{ createlxc_nameservers }}"
      - "createlxc_searchdomains: {{ createlxc_searchdomains }}"
      - "createlxc_net0_bridge: {{ createlxc_net0_bridge }}"
      - "createlxc_net0_ipv4_address: {{ createlxc_net0_ipv4_address }} "
      - "createlxc_net0_ipv4_mask: {{ createlxc_net0_ipv4_mask }}"
      - "createlxc_net0_ipv4_gateway: {{ createlxc_net0_ipv4_gateway }}"
      - "createlxc_net0_mtu: {{ createlxc_net0_mtu }}"
      - "createlxc_net0_mac: {{ createlxc_net0_mac }}"
      - "createlxc_net0_vlanid: {{ createlxc_net0_vlanid }}"
      - "createlxc_netif: {{ createlxc_netif }}  "
      #  root user"
      # - "createlxc_password: {{ createlxc_password }}"
      # - "createlxc_pubkey: {{ createlxc_pubkey }}"
      #  tags "
      - "createlxc_tags: {{ createlxc_tags }}"
      - "createlxc_features: {{ createlxc_features }} "
      - "createlxc_hookscript: {{ createlxc_hookscript }}"
      - "createlxc_timeout: {{ createlxc_timeout }}"
      - "createlxc_timezone: {{ createlxc_timezone }}"
      #  createlxc_purge: false # state=absent"
      #  createlxc_clone: "" # lxc id to clone"
      #  createlxc_vmid: """
