sambafs_default_user: root
sambafs_default_group: root
sambafs_default_mode_dir: '0755'
sambafs_default_mode_file: '0644'
sambafs_conf_dir: /etc/samba
sambafs_usershare_path: /var/lib/samba/usershares
sambafs_dirs:
  - path: "{{ sambafs_usershare_path }}"
    owner: root
    group: sambashare
    mode: '0770'

sambafs_groups: []

sambafs_group_pre: fs
sambafs_group_suf_rw: rw
sambafs_group_suf_ro: ro
sambafs_share_ro_group: ''
sambafs_share_rw_group: ''
sambafs_shares: [] 
sambafs_folders: []
sambafs_users: []
sambafs_folder_public: ''
sambafs_folder_private: ''
