ansibleuser_shell: /usr/local/bin/bash
ansibleuser_sudoers_dir: /usr/local/etc/sudoers.d
ansibleuser_sudoers_visudo: /usr/local/sbin/visudo
ansibleuser_sudoers_owner: root
ansibleuser_sudoers_group: wheel
