- name: Common tasks
  ansible.builtin.include_tasks:
    file: "130_provider_common.yml"
  ignore_errors: true

- name: csr {{ certificates_cert.csr_cn }}
  ansible.builtin.debug:
    msg:
      - "look csr in file: {{ certificates_cert.csr_file | default(certificates_default_csr_file) }}"
      - "look csr in var: certificates_csr_result.csr"
