# certificates_
certificates_list:
    # - csr_cn: "{{ inventory_hostname }}"
    #   csr_san:
    #     - "DNS:{{ inventory_hostname }}"
    #     - "DNS:prx.r.ratners.ru"
    #   provider: certbot
    # - csr_cn: "prx.r.ratners.ru"
    #   provider: certbot
    # - csr_cn: "aaa.r.ratners.ru"
    #   provider: certbot
    - csr_cn: "bbb.r.ratners.ru"
      provider: certbot
      csr_san:
        - "DNS:{{ inventory_hostname }}"  # certbot:
  #   - csr_cn: csr_cn1.certbot.certificates_list
  # csronly:
  #   - csr_cn: csr_cn1.csronly.certificates_list
  # ownca:
  #   - csr_cn: csr_cn1.ownca.certificates_list
  # selfsigned:
  #   - csr_cn: csr_cn1.selfsigned.certificates_list

certificates_default_owner: root
certificates_default_group: root
certificates_default_file_mode: '0644'
certificates_default_dir_mode: '0755'
certificates_default_force: false
certificates_issue: false
certificates_issue_msg: skip certificate issue

certificates_default_root_dir: "/usr/local/etc/pki"
certificates_dirs:
  - path: "{{ certificates_default_root_dir }}"
  - path: "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}"

certificates_default_key_file:       "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}/{{ certificates_default_csr_cn }}.key"
certificates_default_csr_file:       "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}/{{ certificates_default_csr_cn }}.csr"
certificates_default_crt_file:       "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}/{{ certificates_default_csr_cn }}.crt"
certificates_default_fullchain_file: "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}/{{ certificates_default_csr_cn }}-fullchain.pem"
certificates_default_chain_file:     "{{ certificates_default_root_dir }}/{{ certificates_default_csr_cn }}/{{ certificates_default_csr_cn }}-chain.pem"

certificates_default_csr_organizational_unit_name: "IT"
certificates_default_csr_organization_name: "R"
certificates_default_csr_locality_name: "MSK"
certificates_default_csr_country_name: "RU"
certificates_default_csr_email_address: "arsenyratner@gmail.com"
certificates_default_csr_cn: ""
certificates_default_csr_san: []

certificates_default_fetch_dir: "files/pki/{{ certificates_default_csr_cn }}"
certificates_default_fetch_crt: false
certificates_default_fetch_csr: false
certificates_default_fetch_key: false
certificates_default_notify: []

certificates_default_provider: "selfsigned" # csronly acme ownca selfsigned certbot

certificates_default_key_size: 2048
certificates_default_key_type: RSA

certificates_default_ownca_host: "localhost"
certificates_default_ownca_root_dir: "/opt/ca/localhost"
certificates_default_ownca_cacert: "{{ certificates_default_ownca_root_dir }}/localhost.crt"
certificates_default_ownca_cakey: "{{ certificates_default_ownca_root_dir }}/localhost.key"

certificates_default_acme_step2_host: ""
certificates_default_acme_webroot: "/var/www/html"  # + /.well-known/acme-challenge/
certificates_default_acme_account_key: ""
# certificates_default_acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
certificates_default_acme_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
certificates_default_acme_version: 2
certificates_default_acme_challenge: http-01

certificates_default_certbot_root_dir: "/etc/letsencrypt"
certificates_default_certbot_webroot: "/var/www/html"
certificates_certbot_plugins:
  standalone: --standalone
  webroot: --webroot -w {{ certificates_default_certbot_webroot }}
certificates_default_certbot_useplugin: webroot
certificates_default_certbot_deployhook_reloadservices: []

certificates_default_csr_key_usage:
  # (цифровая подпись)
  - digitalSignature
  # (неотказуемость, используется в основном для электронной почты и электронного документооборота)
  # - nonRepudiation
  # (шифрование ключа, используется для обмена сессионными ключами, например в старых версиях TLS)
  # - keyEncipherment
  # (шифрование данных, прямое шифрование пользовательских данных)
  # - dataEncipherment
  # (подпись сертификатов, необходимо для удостоверяющих центров/CA)
  # - keyCertSign
  # (подпись списков отзыва сертификатов, необходимо для управления списками CRL)
  # - cRLSign
  # (согласование ключа, используется в алгоритмах, таких как Диффи-Хеллман, для генерации общего секрета)
  # - keyAgreement
  # (только шифрование, используется только в сочетании с keyAgreement)
  # - encipherOnly
  # (только расшифрование, используется только в сочетании с keyAgreement)
  # - decipherOnly
certificates_default_csr_extended_key_usage:
  # (Аутентификация сервера TLS)
  - serverAuth
  # (Аутентификация клиента TLS)
  # - clientAuth
  # (Подпись кода)
  # - codeSigning
  # (Защита электронной почты)
  # - emailProtection
  # (Штамп времени)
  # - timeStamping
  # (Подпись OCSP)
  # - ocspSigning
  # (Конечная система IPSec)
  # - ipsecEndSystem
  # (Туннель IPSec)
  # - ipsecTunnel
  # (Пользователь IPSec)
  # - ipsecUser
  # (Биометрическая информация)
  # - biometricInfo
  # (Система управления распределенными версиями)
  # - dvcs
  # (Авторизация сервера SGBP)
  # - sbgpCertAAServerAuth
  # (Протокол проверки состояния сертификата)
  # - scvpServer
  # (EAP через PPP)
  # - eapOverPPP
  # (EAP через LAN)
  # - eapOverLAN
