- name: Common tasks
  ansible.builtin.include_tasks:
    file: "30_provider_common.yml"
  ignore_errors: true

- name: csr {{ certreq_csr_cn }}
  ansible.builtin.debug:
    msg:
      - "look csr in file: {{ certreq_csr_file }}"
      - "look csr in var: certreq_csr_result.csr"
