- name: Load a variable file based on the OS type, or a default if not found.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Distribution specific tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Create certificates
  ansible.builtin.include_tasks:
    file: createcert.yml
  loop: "{{ certbot_certificates }}"
  loop_control:
    label: "{{ createcert.name }}"
    loop_var: createcert
