---
- name: create dirs list
  ansible.builtin.set_fact:
    pdmn_nextcloud_dirs: "{{
        pdmn_nextcloud_dirs | default([]) +
        pdmn_nextcloud_item.volumes | map('split', ':') | map('first') | map('community.general.dict_kv', 'path')
      }}"
  loop: "{{ pdmn_nextcloud_containers }}"
  loop_control:
    loop_var: pdmn_nextcloud_item
    label: "{{ pdmn_nextcloud_item.name }}"

- name: Create dirs
  ansible.builtin.file:
    state: directory
    # owner: "{{ pdmn_nextcloud_item.owner | default(pdmn_nextcloud_default_owner) }}"
    # group: "{{ pdmn_nextcloud_item.group | default(pdmn_nextcloud_default_group) }}"
    # mode: "{{ pdmn_nextcloud_item.mode | default(pdmn_nextcloud_default_dir_mode) }}"
    path: "{{ pdmn_nextcloud_item.path }}"
  loop: "{{ pdmn_nextcloud_dirs }}"
  loop_control:
    loop_var: pdmn_nextcloud_item
    label: "{{ pdmn_nextcloud_item.path }}"

- name: Pull images
  containers.podman.podman_image:
    name: "{{ pdmn_nextcloud_item.image }}:{{ pdmn_nextcloud_item.release }}"
    state: present
  loop: "{{ pdmn_nextcloud_containers }}"
  loop_control:
    loop_var: pdmn_nextcloud_item
    label: "{{ pdmn_nextcloud_item.name }}"
  ignore_errors: true

- name: Create pod
  containers.podman.podman_pod:
    state: created
    name: "{{ pdmn_nextcloud_podname }}"
    publish: "{{ pdmn_nextcloud_publish }}"

- name: Run containers
  containers.podman.podman_container:
    state: started
    privileged: true
    pod: "{{ pdmn_nextcloud_item.pod }}"
    name: "{{ pdmn_nextcloud_item.name }}"
    image: "{{ pdmn_nextcloud_item.image }}:{{ pdmn_nextcloud_item.release }}"
    env: "{{ pdmn_nextcloud_item.env | default({}) }}"
    restart_policy: "{{ pdmn_nextcloud_item.restart | default('always') }}"
    requires: "{{ pdmn_nextcloud_item.requires | default([]) }}"
    volume: "{{ pdmn_nextcloud_item.volumes }}"
    healthcheck: "{{ pdmn_nextcloud_item.healthcheck.test[1] | default(omit) }}"
    healthcheck_interval: "{{ pdmn_nextcloud_item.healthcheck.interval | default(omit) }}"
    healthcheck_timeout: "{{ pdmn_nextcloud_item.healthcheck.timeout | default(omit) }}"
    healthcheck_retries: "{{ pdmn_nextcloud_item.healthcheck.retries | default(omit) }}"
  loop: "{{ pdmn_nextcloud_containers }}"
  loop_control:
    loop_var: pdmn_nextcloud_item
    label: "{{ pdmn_nextcloud_item.name }}"
  ignore_errors: true
