postinstall_domainname: ""
postinstall_hostname: "{{ inventory_hostname }}"
postinstall_updatepackages: false
postinstall_selinux: disabled
postinstall_serivces_disabled: []
postinstall_serivces_masked: []
postinstall_timezone: "Europe/Moscow"
postinstall_reboot_auto: false
postinstall_reboot_force: false
postinstall_update: false
postinstall_packages:
  - mc
  - util-linux-extra
postinstall_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8
postinstall_locale_default: en_US.UTF-8
