createlxc_debug: false
createlxc_api_user: "root@pam"
createlxc_api_password: ""
createlxc_api_token_id: ""
createlxc_api_token_secret: ""
createlxc_api_host: ""
createlxc_node: ""
# createlxc_pool: "{{ undef }}"
createlxc_validate_certs: false

# name 
createlxc_vmid: ""
createlxc_hostname: "{{ inventory_hostname }}"
createlxc_description: ""

# root user
createlxc_password: "{{ ansible_password }}" 
createlxc_pubkey: "{{ ansible_ssh_public_key }}"

# start vm after creation
createlxc_startup: []
# createlxc_clone_type: "" # linked | full 
createlxc_unprivileged: true
createlxc_state: started # 
createlxc_force: false
createlxc_update: true # state=present, force=false, clone=omit
createlxc_onboot: false

# template name 
createlxc_ostemplate: 'local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst'
createlxc_ostype: "auto"

# cpu 
createlxc_cpus: 1
# createlxc_cpuunits: 
# memory 
createlxc_memory: 1024 # MB 
createlxc_swap: 2048 # MB
# disk
createlxc_storage: "local-zfs"
createlxc_disk_storage: "{{ createlxc_storage }}"
createlxc_disk_size: 30 # GB
createlxc_disk_opt_volume: ""
createlxc_disk_opt_acl: 1
createlxc_disk_opt_mountoptions: []
createlxc_disk_opt_quota: 0
createlxc_disk_opt_replicate: 0
createlxc_disk_opt_ro: 0
createlxc_disk_opt_shared: 0
createlxc_disk: >-
  {{ createlxc_disk_storage }}:{{ createlxc_disk_size | string }}
  {%- if createlxc_disk_opt_volume != "" %}
  ,volume={{ createlxc_disk_opt_volume }}
  {% endif -%}
  {%- if createlxc_disk_opt_acl != "" -%}
  ,acl={{ createlxc_disk_opt_acl | string }}
  {%- endif -%}
  {%- if createlxc_disk_opt_quota != "" -%}
  ,quota={{ createlxc_disk_opt_quota | string }}
  {%- endif -%}
  {%- if createlxc_disk_opt_replicate != "" -%}
  ,replicate={{ createlxc_disk_opt_replicate | string }}
  {%- endif -%}
  {%- if createlxc_disk_opt_ro != "" -%}
  ,ro={{ createlxc_disk_opt_ro | string }}
  {%- endif -%}
  {%- if createlxc_disk_opt_shared != "" -%}
  ,shared={{ createlxc_disk_opt_shared | string }}
  {%- endif -%}
  {%- if createlxc_disk_opt_mountoptions != [] -%}
  ,mountoptions={{ createlxc_disk_opt_mountoptions | join(';') }}
  {%- endif -%}

createlxc_mounts: {}
createlxc_disk_volume: {}
  # host_path:
  # options:
  # size:
  # storage:
  # volume:
createlxc_mount_volumes: []
  # - host_path:
  #   options:
  #   size:
  #   storage:
  #   volume:
# network
createlxc_nameservers: []
createlxc_searchdomains: []
createlxc_net0_name: eth0
createlxc_net0_bridge: vmbr0
createlxc_net0_ipv4_address: ""
createlxc_net0_ipv4_mask: ""
createlxc_net0_ipv4_gateway: ""
createlxc_net0_ipv6_address: ""
createlxc_net0_ipv6_mask: ""
createlxc_net0_ipv6_gateway: ""
createlxc_net0_mtu: ""
createlxc_net0_mac: ""
createlxc_net0_vlanid: ""
createlxc_net0_firewall: ""
createlxc_net0_type: "veth"
createlxc_netif: 
  net0: >-
    name={{ createlxc_net0_name }}
    {%- if createlxc_net0_bridge != "" -%}
    ,bridge={{ createlxc_net0_bridge }}
    {%- endif -%}
    {%- if createlxc_net0_ipv4_address == "" -%}
    ,ip=dhcp
    {%- endif -%}
    {%- if createlxc_net0_ipv4_address != ""-%}
    ,ip={{ createlxc_net0_ipv4_address }}/{{ createlxc_net0_ipv4_mask }}
    {%- endif -%}
    {%- if createlxc_net0_ipv4_gateway != ""-%}
    ,gw={{ createlxc_net0_ipv4_gateway }}
    {%- endif -%}
    {%- if createlxc_net0_ipv6_address != ""-%}
    ,ip6={{ createlxc_net0_ipv6_address }}/{{ createlxc_net0_ipv6_mask }}
    {%- endif -%}
    {%- if createlxc_net0_ipv6_gateway != ""-%}
    ,gw6={{ createlxc_net0_ipv6_gateway }}
    {%- endif -%}
    {%- if createlxc_net0_mtu != "" -%}
    ,mtu={{ createlxc_net0_mtu }}
    {%- endif -%}
    {%- if createlxc_net0_vlanid != "" -%}
    ,tag={{ createlxc_net0_vlanid }}
    {%- endif -%}
    {%- if createlxc_net0_mac != "" -%}
    ,hwaddr={{ createlxc_net0_mac }}
    {%- endif -%}
    {%- if createlxc_net0_firewall != "" -%}
    ,firewall={{ createlxc_net0_firewall }},
    {%- endif -%}

# tags 
createlxc_tags: []

createlxc_features: 
  - "nesting=1"
createlxc_hookscript: ""
createlxc_timeout: 30
createlxc_timezone: host
# createlxc_purge: false # state=absent
# createlxc_clone: "" # lxc id to clone
