---
- name: First dc
  hosts: role_firstdc
  roles:
    - general-redos
  tasks:
    - name: Role sambadc
      vars:
        sambadc_deploy_firstdc: true
        sambadc_deploy_adddc: false
      ansible.builtin.include_role:
        name: sambadc-redos

    - name: Role bind
      ansible.builtin.include_role:
        name: bind9-redos

    - name: Setup DNS settings
      ansible.builtin.include_role:
        name: network-redos
      vars:
        network_ipv4_method: dnsonly
