---
- name: Add DC
  hosts: role_dc,!role_firstdc
  tasks:
    - name: Role sambadc
      ansible.builtin.include_role:
        name: sambadc-redos

    - name: Role bind
      ansible.builtin.include_role:
        name: bind9-redos

    - name: Setup DNS settings
      ansible.builtin.include_role:
        name: network-redos
      vars:
        network_ipv4_method: dnsonly
